I asked ChatGPT to assess my skills on Numpy. Hence ChatGPT generated multiple questions starting from basics to advanced concepts. As it's a new learning. I am recording all those learnings in this note book.

Q1.Create an Numpy array from List

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

Q2.What is the difference between np.array([1,2,3]) and np.asarray([1,2,3])?

np.array() --> always creates a new array even if the input is already a numpy array
np.asarray() --> creates a new array if the input isn't already a numpy array. if you pass an existing Numpy array - it returns the same object without copying it.

In [4]:
arr1 = np.array([1,2,3]) # Creates a new object
arr2 = np.array(arr1)    # Creates a new object. It copies the arr1 into arr2
arr3 = np.asarray(arr1)  # Returns hte same object, no copy has made.

print(arr1 is arr2)      #False indicates - both are not the same object
print(arr1 is arr3)      #True indicates - both are same object.

False
True


In [7]:
arr3[0] = 10
arr2[1] = 100
arr3

array([10,  2,  3])

In [8]:
arr1

array([10,  2,  3])

arr3's first element is changed to 10. But we can also see that arr1 is updated.
arr2's second element is changed to 100. But as there is no dependency between arr2 & arr1. these changes are not propagated.
np.asarray() --> is more memory efficient

Q3.How do you create a 5×5 matrix filled with zeros in NumPy?

In [11]:
five_five_zeros = np.zeros((5,5)) #Zeros creates zero matrix and shape(tuple) controls number of rows and columns
five_five_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Q4.What does np.linspace(0, 10, 5) return?

np.linspace(start,stop,num) generates num of evenly spaced values between start and stop, including both endpoints.

In [14]:
np.linspace(1,13,7) #start:1, stop:13(included), num: Need to generate 5 points

array([ 1.,  3.,  5.,  7.,  9., 11., 13.])

np.arange(start,stop,step) generate values from start with an increment/decrement of step. but don't include the stop value in it.

In [15]:
np.arange(1,15,2) #start:1, stop:15(not included),step:+2

array([ 1,  3,  5,  7,  9, 11, 13])

Q5. What function is used to check the shape of a NumPy array?

In [17]:
arr1.shape #shape gives the dimentions of Numpy Array. But we must not call this as .shape()
# shape is an attribute, not a method

(3,)

Q6. Given arr = np.array([10, 20, 30, 40, 50]), how do you access the third element?

In [19]:
arr = np.array([10, 20, 30, 40, 50])
arr[2] #Numpy uses Zero-based indexing. 

30

Q7. arr = np.array([10, 20, 30, 40, 50]), how do you retrieve the last two elements?

In [22]:
arr[3:] #as we know the size of the array #Positive indexing

array([40, 50])

In [23]:
# Or we can use arr[-2:], will acess the last two elements
arr[-2:] #Negative indexing

array([40, 50])

Q8. Given the following 2D NumPy array, how do you extract the second row?

In [25]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [26]:
arr[1,:] #Row index, column index
# 1 --> indicates the second row
# : --> indicates all the columns

array([4, 5, 6])

In [27]:
arr[1] # NumPy automatically assumes all columns when only the row index is provided.

array([4, 5, 6])

Q9. Given the same 2D NumPy array, how do you extract only the first two rows and the last two columns?

In [28]:
arr[:2,-2:]

array([[2, 3],
       [5, 6]])

Q10. Given the following 2D NumPy array, how do you extract all even numbers?

In [32]:
arr = np.array([[10, 15, 20], 
                [25, 30, 35], 
                [40, 45, 50]])
even_array = arr[arr%2==0] #arr%2==0 creates a boolean matrix. 
# Boolean array supplied to array, it will retrieve only the filtered values into a 1D array

In [33]:
even_array

array([10, 20, 30, 40, 50])

In [34]:
# NumPy uses boolean indexing to filter elements efficiently without loops.
# The result is a 1D array of even numbers.

Q11. Given the following NumPy array, replace all odd numbers with -1 while keeping even numbers unchanged.

In [ ]:
arr = np.array([[10, 15, 20], 
                [25, 30, 35], 
                [40, 45, 50]])
arr[arr%2!=0] = -1 #
arr

array([[10, -1, 20],
       [-1, 30, -1],
       [40, -1, 50]])

In [36]:
# NumPy’s boolean indexing makes element-wise modifications super efficient—no loops needed!
# arr[arr % 2 != 0] = -1 directly updates the original array in-place.

Q12. Normalize the given NumPy array so that all values are scaled between 0 and 1.
Formula for Min-Max Normalization:

X_normalized = (X-X_min)/(X_max-X_min)

In [37]:
arr = np.array([[10, 15, 20], 
                [25, 30, 35], 
                [40, 45, 50]])
arr = (arr - arr.min())/(arr.max()-arr.min())
arr

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [38]:
# arr.min() → Finds the minimum value in the array.
# arr.max() → Finds the maximum value in the array.

* Min-Max Normalization scales values between 0 and 1, making them comparable across different ranges.
* Useful in Machine Learning, especially for algorithms like KNN, SVM, and Neural Networks, where feature scaling improves performance.

Q13. Replace all values in the given array that are greater than 30 with 100.

In [40]:
arr = np.array([[10, 15, 35], 
                [25, 30, 40], 
                [45, 20, 50]])
arr[arr>30]=100 #arr[condition] = assigning_value
arr

array([[ 10,  15, 100],
       [ 25,  30, 100],
       [100,  20, 100]])

Q14. Find the mean, median, and standard deviation of the given NumPy array.
np.mean(arr) → Calculates the average of all elements in the array.
np.median(arr) → Finds the middle value when the elements are sorted.
np.std(arr) → Computes the standard deviation, which measures data spread.

In [42]:
arr = np.array([[10, 15, 35], 
                [25, 30, 40], 
                [45, 20, 50]])
mean_val = np.mean(arr)
median = np.median(arr)
std_dev_val = np.std(arr)
print(f'Mean of array is:{mean_val}')
print(f'Median of array is:{median}')
print(f'Standard Deviation of array is:{std_dev_val}')

Mean of array is:30.0
Median of array is:30.0
Standard Deviation of array is:12.909944487358056


Q15. Find the row-wise and column-wise sum of the given NumPy array.

In [48]:
arr = np.array([[10, 15, 35], 
                [25, 30, 40], 
                [45, 20, 50]])
row_wise_sum = np.sum(arr,axis=1) #row_wise, axis=1
column_wise_sum = np.sum(arr,axis=0) #column_wise, axis=0

In [49]:
row_wise_sum

array([ 60,  95, 115])

In [50]:
column_wise_sum

array([ 80,  65, 125])

Q16. Reshape the given 1D NumPy array into a 3×3 matrix.

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape((3,3)) #reshape takes a tuple (rows, columns) as a parameter.
# New shape must be compatible with the number of elements.
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q17. Flatten the given 2D NumPy array into a 1D array.

In [56]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr = arr.flatten()
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Q18. Stack two NumPy arrays vertically and horizontally.

In [58]:
arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8]])
row_stack = np.vstack((arr1,arr2)) #Verically stacking #row-wise stacking
column_stack = np.hstack((arr1,arr2)) #Horizontally stacking #column-wise stacking

In [59]:
row_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
column_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Q19. Given a 5x5 matrix, replace all values in the 3rd row with -1.

In [62]:
arr = np.arange(1, 26).reshape(5, 5) 
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
arr[2,:]=-1 #Assigning all the third row elements to -1

In [68]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [-1, -1, -1, -1, -1],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Q20. replace all elements in the last column with 99 using a similar slicing technique!

In [71]:
arr[:,-1] = 99 #assigning last column elements to 99
arr

array([[ 1,  2,  3,  4, 99],
       [ 6,  7,  8,  9, 99],
       [-1, -1, -1, -1, 99],
       [16, 17, 18, 19, 99],
       [21, 22, 23, 24, 99]])

Q21. swap the first and last rows in the matrix without using a temporary variable.

In [72]:
arr[[0,-1]] = arr[[-1,0]] #Swaping the first row with last row & last row with first row
arr

array([[21, 22, 23, 24, 99],
       [ 6,  7,  8,  9, 99],
       [-1, -1, -1, -1, 99],
       [16, 17, 18, 19, 99],
       [ 1,  2,  3,  4, 99]])

Q22. flipping the entire matrix upside down using a single NumPy command!

In [74]:
arr = np.flip(arr,0) #Row-wise flipping axis=0
arr

array([[ 1,  2,  3,  4, 99],
       [16, 17, 18, 19, 99],
       [-1, -1, -1, -1, 99],
       [ 6,  7,  8,  9, 99],
       [21, 22, 23, 24, 99]])

Q23. flip the matrix left to right (horizontally) using a single NumPy command!

In [75]:
arr = np.flip(arr,axis=1) #Column wise flipping axis=1

In [76]:
arr

array([[99,  4,  3,  2,  1],
       [99, 19, 18, 17, 16],
       [99, -1, -1, -1, -1],
       [99,  9,  8,  7,  6],
       [99, 24, 23, 22, 21]])

Q24. rotate the matrix 90 degrees counterclockwise using a single NumPy command!

In [78]:
arr = np.rot90(arr)

In [79]:
arr

array([[ 1, 16, -1,  6, 21],
       [ 2, 17, -1,  7, 22],
       [ 3, 18, -1,  8, 23],
       [ 4, 19, -1,  9, 24],
       [99, 99, 99, 99, 99]])

In [80]:
# Counterclockwise (default): np.rot90(arr, k=1)
# 180-degree rotation: np.rot90(arr, k=2)
# Clockwise rotation (90 degrees): np.rot90(arr

Q25. flip the matrix along the main diagonal (transpose it) using a NumPy function!

In [82]:
arr = arr.T
arr

array([[ 1,  2,  3,  4, 99],
       [16, 17, 18, 19, 99],
       [-1, -1, -1, -1, 99],
       [ 6,  7,  8,  9, 99],
       [21, 22, 23, 24, 99]])

Q26. find the unique elements in a NumPy array and return them in sorted order!

In [83]:
np.unique(arr)

array([-1,  1,  2,  3,  4,  6,  7,  8,  9, 16, 17, 18, 19, 21, 22, 23, 24,
       99])